---
galaxy_info:
  author: Sandeep
  description: Install and configure Nginx web server
  company: Ai Learners India
  license: MIT
  min_ansible_version: "2.15"
  galaxy_tags:
    - nginx
    - web
    - webserver

dependencies: []
